"""notes — music as code.

A composition is a Python program. The language (`notes.lang`) builds an immutable music
tree; `perform` flattens it into the intermediate representation (`notes.ir.Score`, exact
and serialisable); the engine (`notes.engine`) renders the IR to audio. ``from notes
import *`` brings in the whole DSL: notation, theory, instruments, effects and `Song`.
"""

__version__ = "0.1.0"

from notes.engine import (
    EQ,
    FM,
    AcousticGuitar,
    Bass,
    BassGuitar,
    Bell,
    Body,
    Cabinet,
    Chorus,
    Compressor,
    Delay,
    Drive,
    DrumKit,
    ElectricGuitar,
    EPiano,
    Filter,
    GuitarAmp,
    Lead,
    Noise,
    Pad,
    Pluck,
    RenderResult,
    Reverb,
    RockKit,
    Room,
    Synth,
    render_score,
)
from notes.ir import Score
from notes.lang import (
    E,
    H,
    Key,
    Music,
    Note,
    Q,
    Rest,
    S,
    Song,
    T,
    Track,
    W,
    bars,
    beats,
    cat,
    chord,
    chord_pitches,
    chords,
    dotted,
    euclid,
    hit,
    melody,
    midi_to_hz,
    parse_pitch,
    pitch_name,
    place,
    stack,
    steps,
    triplet,
    voice_lead,
)

__all__ = [
    "EQ",
    "FM",
    "AcousticGuitar",
    "Bass",
    "BassGuitar",
    "Bell",
    "Body",
    "Cabinet",
    "Chorus",
    "Compressor",
    "Delay",
    "Drive",
    "DrumKit",
    "E",
    "EPiano",
    "ElectricGuitar",
    "Filter",
    "GuitarAmp",
    "H",
    "Key",
    "Lead",
    "Music",
    "Noise",
    "Note",
    "Pad",
    "Pluck",
    "RockKit",
    "Q",
    "RenderResult",
    "Rest",
    "Reverb",
    "Room",
    "S",
    "Score",
    "Song",
    "Synth",
    "T",
    "Track",
    "W",
    "bars",
    "beats",
    "cat",
    "chord",
    "chord_pitches",
    "chords",
    "dotted",
    "euclid",
    "hit",
    "melody",
    "midi_to_hz",
    "parse_pitch",
    "pitch_name",
    "place",
    "render_score",
    "stack",
    "steps",
    "triplet",
    "voice_lead",
]
